name: Deployment of EC2 Instance with Custom AMI

on:
  workflow_dispatch:
    inputs:
        custom_ami_version:
            description: "Enter required custom_ami_version"
            required: true
jobs:
    ec2_deploy:
        name: ec2_deploy
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: terraform
        steps:

            
            - name: Checkout Repository
              uses: actions/checkout@v4

            
            - name: Terraform Workflow
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.9.8"
                cli_config_credentials_token: ${{ secrets.TF_CLOUD_API_TOKEN }}

            
            - name: Terraform Init
              id: init
              run: terraform init

            
            - name: Terraform Plan
              id: plan
              run: terraform plan -var "custom_ami_version=${{ inputs.ami_version }}" -no-color
              continue-on-error: true

            
            - name: Terraform Apply
              id: Apply
              run: terraform apply -var "custom_ami_version=${{ inputs.ami_version }}" -auto-approve

          # - name: Terraform Outputs
          #   id: tf_out
          #   run: |
          #     echo "ec2_ip=$(terraform output webapp_public_ip | tr -d '""')" >> "$GITHUB_OUTPUT"